namespace Zen.GuiControls
{
    public enum ParentContainerAlignment
    {
        ParentTopLeftAlignsWithChildTopLeft,
        ParentTopLeftAlignsWithChildMiddleLeft,
        ParentTopLeftAlignsWithChildBottomLeft,
        ParentTopLeftAlignsWithChildTopCenter,
        ParentTopLeftAlignsWithChildMiddleCenter,
        ParentTopLeftAlignsWithChildBottomCenter,
        ParentTopLeftAlignsWithChildTopRight,
        ParentTopLeftAlignsWithChildMiddleRight,
        ParentTopLeftAlignsWithChildBottomRight,

        ParentMiddleLeftAlignsWithChildTopLeft,
        ParentMiddleLeftAlignsWithChildMiddleLeft,
        ParentMiddleLeftAlignsWithChildBottomLeft,
        ParentMiddleLeftAlignsWithChildTopCenter,
        ParentMiddleLeftAlignsWithChildMiddleCenter,
        ParentMiddleLeftAlignsWithChildBottomCenter,
        ParentMiddleLeftAlignsWithChildTopRight,
        ParentMiddleLeftAlignsWithChildMiddleRight,
        ParentMiddleLeftAlignsWithChildBottomRight,

        ParentBottomLeftAlignsWithChildTopLeft,
        ParentBottomLeftAlignsWithChildMiddleLeft,
        ParentBottomLeftAlignsWithChildBottomLeft,
        ParentBottomLeftAlignsWithChildTopCenter,
        ParentBottomLeftAlignsWithChildMiddleCenter,
        ParentBottomLeftAlignsWithChildBottomCenter,
        ParentBottomLeftAlignsWithChildTopRight,
        ParentBottomLeftAlignsWithChildMiddleRight,
        ParentBottomLeftAlignsWithChildBottomRight,

        ParentTopCenterAlignsWithChildTopLeft,
        ParentTopCenterAlignsWithChildMiddleLeft,
        ParentTopCenterAlignsWithChildBottomLeft,
        ParentTopCenterAlignsWithChildTopCenter,
        ParentTopCenterAlignsWithChildMiddleCenter,
        ParentTopCenterAlignsWithChildBottomCenter,
        ParentTopCenterAlignsWithChildTopRight,
        ParentTopCenterAlignsWithChildMiddleRight,
        ParentTopCenterAlignsWithChildBottomRight,

        ParentMiddleCenterAlignsWithChildTopLeft,
        ParentMiddleCenterAlignsWithChildMiddleLeft,
        ParentMiddleCenterAlignsWithChildBottomLeft,
        ParentMiddleCenterAlignsWithChildTopCenter,
        ParentMiddleCenterAlignsWithChildMiddleCenter,
        ParentMiddleCenterAlignsWithChildBottomCenter,
        ParentMiddleCenterAlignsWithChildTopRight,
        ParentMiddleCenterAlignsWithChildMiddleRight,
        ParentMiddleCenterAlignsWithChildBottomRight,

        ParentBottomCenterAlignsWithChildTopLeft,
        ParentBottomCenterAlignsWithChildMiddleLeft,
        ParentBottomCenterAlignsWithChildBottomLeft,
        ParentBottomCenterAlignsWithChildTopCenter,
        ParentBottomCenterAlignsWithChildMiddleCenter,
        ParentBottomCenterAlignsWithChildBottomCenter,
        ParentBottomCenterAlignsWithChildTopRight,
        ParentBottomCenterAlignsWithChildMiddleRight,
        ParentBottomCenterAlignsWithChildBottomRight,

        ParentTopRightAlignsWithChildTopLeft,
        ParentTopRightAlignsWithChildMiddleLeft,
        ParentTopRightAlignsWithChildBottomLeft,
        ParentTopRightAlignsWithChildTopCenter,
        ParentTopRightAlignsWithChildMiddleCenter,
        ParentTopRightAlignsWithChildBottomCenter,
        ParentTopRightAlignsWithChildTopRight,
        ParentTopRightAlignsWithChildMiddleRight,
        ParentTopRightAlignsWithChildBottomRight,

        ParentMiddleRightAlignsWithChildTopLeft,
        ParentMiddleRightAlignsWithChildMiddleLeft,
        ParentMiddleRightAlignsWithChildBottomLeft,
        ParentMiddleRightAlignsWithChildTopCenter,
        ParentMiddleRightAlignsWithChildMiddleCenter,
        ParentMiddleRightAlignsWithChildBottomCenter,
        ParentMiddleRightAlignsWithChildTopRight,
        ParentMiddleRightAlignsWithChildMiddleRight,
        ParentMiddleRightAlignsWithChildBottomRight,

        ParentBottomRightAlignsWithChildTopLeft,
        ParentBottomRightAlignsWithChildMiddleLeft,
        ParentBottomRightAlignsWithChildBottomLeft,
        ParentBottomRightAlignsWithChildTopCenter,
        ParentBottomRightAlignsWithChildMiddleCenter,
        ParentBottomRightAlignsWithChildBottomCenter,
        ParentBottomRightAlignsWithChildTopRight,
        ParentBottomRightAlignsWithChildMiddleRight,
        ParentBottomRightAlignsWithChildBottomRight,
    }
}